server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: '1qa2ws'
    url: jdbc:h2:file:./notes
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  file: ./logs/notes.log
  level: info

endpoints:
  actuator:
    sensitive: false
  shutdown:
    enabled: true
  enabled: false
  info:
    enabled: false
management:
  security:
    enabled: false


