server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./notes
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  file: ./logs/notes.log
  level: info


